### ISSUE TITLE
[FEATURE REQUEST] Add Player Model Heavy + Flags Option

### ISSUE THREAD

**Issue by crashzk** [rogeraabbccdd/CSGO-PlayerModel#1]
First of all I would like to thank you for making this plugin available to everyone. And congratulate you for the plugin, recently I have been following you closely, only this one has great launching plugins, this is proof of one more.

About the suggestion, from what I saw testing the plugin, I just missed the Heavy Player Models, here is a print showing the models in question that I'm talking about.

https://prnt.sc/rb289o

Would it be possible to include these Player Models in the plugin as well?

And another suggestion would be to add the flag option in the config? Would be like this:
```
"Anarchist [1]"
		{
			"skin"	"models/player/custom_player/legacy/tm_anarchist.mdl"
			"arms"	"models/weapons/t_arms_anarchist.mdl"
			"flags"	"a"
		}
```
Because this suggestion, if you add Models Player Heavy, it would be good to be able to control who would have access to this model, since everyone can go out and get it.

I say that, because I think it was by default you can come with your collection larger than the standard, as it is so in the official game modes of CSGO / Valve, ~~as I recall~~.

And again, thanks for sharing another great plugin.

**Comment by rogeraabbccdd** [comment]
You can add any models you want in config, including custom models.

**Comment by rogeraabbccdd** [comment]
And I will NOT add flag support in this plugin, because it is designed for my server.
